### ISSUE TITLE
Subscription callback timeout

### ISSUE THREAD

**Issue by ptgamr** [nicoolas25/realtime-api-explorer#1]
Hi @nicoolas25 , thanks for your work!

I've installed your application on my server. But doing the POST to `/app_id/subscriptions` give me timeout error:

```
{
  "error": {
    "message": "(#2200) callback verification failed: Operation timed out after 5445 milliseconds with 9 out of 19 bytes received",
    "type": "OAuthException",
    "code": 2200
  }
}
```

This is the callback doman: http://bigbang.trinhtrunganh.com

I saw Facebook send the request to my server, but that error is still happened

http://bigbang.trinhtrunganh.com/?hub.mode=subscribe&hub.challenge=488343959&hub.verify_token=realtime-explorer-token

Do you have any idea on this?

Thanks!

**Comment by ptgamr** [comment]
Here is what I got from the logs:

```
127.0.0.1 - - [22/Jul/2015:00:40:29 -0400] "GET /?hub.mode=subscribe&hub.challenge=1638957536&hub.verify_token=realtime-explorer-token HTTP/1.1" 200 - 0.0006
[2015-07-22 00:40:29] WARN  chunked is set for an HTTP/1.0 request. (ignored)
```

**Comment by nicoolas25** [comment]
Hello @ptgamr, I have an `unknown host` when I try `ping trinhtrunganh.com`. I think it is a setup issue. Facebook fails to validate the given `callback_url`. For the validation, Facebook sends a `GET` request to the given URL...

Can you reach and get a response from the application from an external network? The response you get from the `GET` request must have in the body the value of the `hub.challenge` parameter.

You've got something in the server log, this is definitely something good ^^

**Comment by nicoolas25** [comment]
Hello @ptgamr, I have an `unknown host` when I try `ping trinhtrunganh.com`. I think it is a setup issue. Facebook fails to validate the given `callback_url`. For the validation, Facebook sends a `GET` request to the given URL...

Can you reach and get a response from the application from an external network? The response you get from the `GET` request must have in the body the value of the `hub.challenge` parameter.

You've got something in the server log, this is definitely something good ^^

**Comment by ptgamr** [comment]
That's really strange that you can not `ping trinhtrunganh.com`. However I figured it out the reason why.

I run your rack server in a digital ocean $5, so it can not handle multiple requests at the same time. And Facebook do send multiple callbacks for endpoint validation.

I run your code on another server, and it's fine. Problem sovled. Credited to this SO thread: http://stackoverflow.com/questions/17530464/facebook-realtime-updates-subscription-verification-in-python

Thanks for your help while being at the beach. Really appreciated!

**Comment by nicoolas25** [comment]
Hello @ptgamr, I have an `unknown host` when I try `ping trinhtrunganh.com`. I think it is a setup issue. Facebook fails to validate the given `callback_url`. For the validation, Facebook sends a `GET` request to the given URL...

Can you reach and get a response from the application from an external network? The response you get from the `GET` request must have in the body the value of the `hub.challenge` parameter.

You've got something in the server log, this is definitely something good ^^

**Comment by nicoolas25** [comment]
I'm glad you solved this. I hope this small app will be useful to you!
